version: '2'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - ./server/nginx.conf:/etc/nginx/nginx.conf
        #- /var/www/html/shared:/var/www/
        #- /etc/letsencrypt:/etc/letsencrypt
        #- /root/letsencrypt/lib:/var/lib/letsencrypt
    depends_on:
      - node
  node:
    build: .
    ports:
      - "8080:8080"
    env_file: ./server/.env.production
    depends_on:
      - eth
      - redis
  eth:
    image: foamspace/cliquebait:latest
    ports:
      - "8545:8545"
    environment:
      EXTERNAL_ALLOCS: 0xC7679A8C55817EFA649961C6d9DF7596e4bd8C51
      ACCOUNTS_TO_CREATE: 5
      ALLOC_WEI: 0xFFFFFFFFFFFFFFFFFFFF
    volumes:
      - ./cbdata:/cbdata
  redis:
    image: redis
    ports:
      - "6379:6379"
