version: '2'
services:
  node:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    env_file: ./server/.env.production
    volumes:
      - ./server/.env.production:/usr/src/app/server/.env
      # TODO web server for letsencrypt only
      #- /etc/letsencrypt:/etc/letsencrypt #uncomment for production HTTPS
      #- /root/letsencrypt/lib:/var/lib/letsencrypt #uncomment for production HTTPS
    depends_on:
      - eth
      - redis

  eth:
    build: ./geth
    restart: unless-stopped
    ports:
      - "8545:8545"
    volumes:
      - ./geth/cbdata:/cbdata

  # just for Node web session storage, currently
  redis:
    image: redis
    ports:
      - "6379:6379"