version: '2'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - ./server/nginx.conf:/etc/nginx/nginx.conf
        #- /var/www/html/shared:/var/www/ # uncomment if running on Linux
        #- /etc/letsencrypt:/etc/letsencrypt #uncomment for production HTTPS
        #- /root/letsencrypt/lib:/var/lib/letsencrypt #uncomment for production HTTPS
    depends_on:
      - node

  node:
    build: .
    ports:
      - "8080:8080"
    env_file: ./server/.env.production
    volumes:
      - ./server/.env.production:/usr/src/app/server/.env
      - ./web/.env.production:/usr/src/app/web/.env
    depends_on:
      - eth
      - redis

  eth:
    build: ./geth
    ports:
      - "8545:8545"

  # just for Node web session storage, currently
  redis:
    image: redis
    ports:
      - "6379:6379"
